<?php

use Illuminate\Database\Seeder;

class m_productsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m_products')->insert([
            [
                'product_name' => 'いちご1kg',
                'category_id' => '1',
                'description' => '栃木県産のあま~いいちごです｡',
                'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
                'price' => '2000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '1',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'いちご2kg',
                'category_id' => '1',
                'description' => '栃木県産のあま~いいちごです｡',
                'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
                'price' => '3900',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '1',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'いちご3kg',
                'category_id' => '1',
                'description' => '栃木県産のあま~いいちごです｡',
                'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
                'price' => '5500',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '1',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'おまかせお魚セット3kg',
                'category_id' => '2',
                'description' => 'その日に穫れたお魚を急速冷凍した詰め合わせです｡',
                'recommend_comment' => '新鮮な状態で急速冷凍したので鮮度が違います｡',
                'price' => '5000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '4',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'おまかせお魚セット5kg',
                'category_id' => '2',
                'description' => 'その日に穫れたお魚を急速冷凍した詰め合わせです｡',
                'recommend_comment' => '釣りたてを急速冷凍!!',
                'price' => '7000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '4',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'ボイルたらば2kg',
                'category_id' => '2',
                'description' => 'その日に穫れたタラバガニを急速冷凍しました｡',
                'recommend_comment' => '急速冷凍で旨味が残ってます!!',
                'price' => '7000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '4',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '大間産マグロ大トロ2kg',
                'category_id' => '2',
                'description' => '天然物は脂の旨味が違います｡',
                'recommend_comment' => '伝説の漁師が仕留めたマグロ!!味はまさに伝説級',
                'price' => '7000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '4',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '神戸牛ロース1kg',
                'category_id' => '3',
                'description' => 'A5ランクのお肉｡サシがきれいに入ってます',
                'recommend_comment' => '最高級のお肉でステーキはいかがですか!?',
                'price' => '10000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '3',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '神戸牛ロース2kg',
                'category_id' => '3',
                'description' => 'A5ランクのお肉｡サシがきれいに入ってます｡',
                'recommend_comment' => '最高級のお肉でステーキはいかがですか!?',
                'price' => '20000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '3',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '神戸牛たん2kg',
                'category_id' => '3',
                'description' => '牛タンそのまま1本!タン塩いかがすか~?',
                'recommend_comment' => '夢の厚切りタン塩に挑戦!!',
                'price' => '14000',
                'sale_status_id' => '1',
                'product_status_id' => '2',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '3',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '夕張メロン3個',
                'category_id' => '1',
                'description' => '夕張メロンです｡甘い~',
                'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
                'price' => '10000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '2',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'カラフルミニトマト3kg',
                'category_id' => '2',
                'description' => '甘いカラフルミニトマト!',
                'recommend_comment' => '見た目も味もいい!!ご賞味ください!!',
                'price' => '5000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '2',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '旬のアスパラ3kg',
                'category_id' => '2',
                'description' => 'とってもおいしいアスパラです',
                'recommend_comment' => '朝もぎでそのまま送るから鮮度抜群!!',
                'price' => '5000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '2',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '雪室じゃがいも3kg',
                'category_id' => '2',
                'description' => '雪室で熟成させたじゃがいもです',
                'recommend_comment' => '低音でじっくり熟成させました!!',
                'price' => '2000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '2',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '男米10kg',
                'category_id' => '5',
                'description' => '福島男米です',
                'recommend_comment' => '2021年の福島の新米です!!',
                'price' => '3000',
                'sale_status_id' => '2',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '5',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '日本酒6本セット',
                'category_id' => '6',
                'description' => '福島男米で作った日本酒です',
                'recommend_comment' => '福島のお米で作った日本酒です!!',
                'price' => '3000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '5',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '米ぬか石鹸',
                'category_id' => '7',
                'description' => '米ぬかで作った石鹸です',
                'recommend_comment' => 'お肌ツルツル間違いなし!',
                'price' => '1200',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '5',
                'delete_flag' => '0',
            ],
            [
                'product_name' => '牛肉しぐれ煮',
                'category_id' => '7',
                'description' => '神戸牛をしぐれ煮にしました',
                'recommend_comment' => 'A5ランクの神戸牛で作った贅沢しぐれ煮!!',
                'price' => '3000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '3',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'トマトジュース',
                'category_id' => '7',
                'description' => 'トマトジュース',
                'recommend_comment' => '無農薬の美味しいトマトをジュースにしました',
                'price' => '2200',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '2',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'いちごジャム',
                'category_id' => '7',
                'description' => 'とちおとめを使ったジャムです',
                'recommend_comment' => 'とちおとめで作ったジャムです!!',
                'price' => '2500',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '1',
                'delete_flag' => '0',
            ],
            [
                'product_name' => 'お魚フレーク',
                'category_id' => '7',
                'description' => '新鮮なお魚をフレークにしました',
                'recommend_comment' => '新鮮なお魚をフレークに!絶妙な味付けでご飯がすすみます!',
                'price' => '1400',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '4',
                'delete_flag' => '0',
            ],
        ]);
    }
}
