<?php

use Illuminate\Database\Seeder;

class m_productsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m_products')->insert([
            [
                'product_name' => 'いちご1kg',
                'category_id' => '1',
                'description' => '栃木県産のあま~いいちごです｡',
                'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
                'price' => '2000',
                'sale_status_id' => '1',
                'product_status_id' => '1',
                'regist_date' => date('Y-m-d H:i:s'),
                'product_image_url' => 'no_image.jpg',
                'seller_id' => '1',
                'delete_flag' => '0',
            ],
            // [
            //     'product_name' => 'いちご2kg',
            //     'category_id' => '0',
            //     'price' => '3900',
            //     'description' => '栃木県産のあま~いいちごです｡',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '1',
            //     'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'いちご3kg',
            //     'category_id' => '0',
            //     'price' => '5500',
            //     'description' => '栃木県産のあま~いいちごです｡',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '1',
            //     'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'おまかせお魚セット3kg',
            //     'category_id' => '2',
            //     'price' => '5000',
            //     'description' => 'その日に穫れたお魚を急速冷凍した詰め合わせです｡',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '2',
            //     'recommend_comment' => '新鮮な状態で急速冷凍したので鮮度が違います｡',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'おまかせお魚セット5kg',
            //     'category_id' => '2',
            //     'price' => '7000',
            //     'description' => 'その日に穫れたお魚を急速冷凍した詰め合わせです｡',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '2',
            //     'recommend_comment' => '新鮮な状態で急速冷凍したので鮮度が違いますよ!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'ボイルたらば2kg',
            //     'category_id' => '2',
            //     'price' => '7000',
            //     'description' => 'その日に穫れたタラバガニを急速冷凍しました｡',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '2',
            //     'recommend_comment' => '急速冷凍で旨味が残ってます!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '神戸牛ロース1kg',
            //     'category_id' => '3',
            //     'price' => '10000',
            //     'description' => 'A5ランクのお肉｡サシがきれいに入ってます',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '3',
            //     'recommend_comment' => '最高級のお肉でステーキはいかがですか!?',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '神戸牛ロース2kg',
            //     'category_id' => '3',
            //     'price' => '20000',
            //     'description' => 'A5ランクのお肉｡サシがきれいに入ってます｡',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '3',
            //     'recommend_comment' => '最高級のお肉でステーキはいかがですか!?',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '神戸牛たん2kg',
            //     'category_id' => '3',
            //     'price' => '14000',
            //     'description' => '牛タンそのまま1本!タン塩いかがすか~?',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '2',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '3',
            //     'recommend_comment' => '夢の厚切りタン塩に挑戦!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '夕張メロン3個',
            //     'category_id' => '0',
            //     'price' => '10000',
            //     'description' => '夕張メロンです｡甘い~',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '4',
            //     'recommend_comment' => '糖度20度!!!この甘さに衝撃受けてください',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'カラフルミニトマト3kg',
            //     'category_id' => '1',
            //     'price' => '5000',
            //     'description' => '甘いカラフルミニトマト!',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '4',
            //     'recommend_comment' => '見た目も味もいい!!ご賞味ください!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '旬のアスパラ3kg',
            //     'category_id' => '1',
            //     'price' => '5000',
            //     'description' => 'とってもおいしいアスパラです',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '4',
            //     'recommend_comment' => '朝もぎでそのまま送るから鮮度抜群!!ご賞味ください!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '雪室じゃがいも3kg',
            //     'category_id' => '1',
            //     'price' => '2000',
            //     'description' => '雪室で熟成させたじゃがいもです',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '4',
            //     'recommend_comment' => '低音でじっくり熟成させました!!驚きの甘さをご賞味ください!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'こしひかり10kg',
            //     'category_id' => '4',
            //     'price' => '3000',
            //     'description' => '新潟こしひかりです',
            //     'sale_status_id' => '2',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '5',
            //     'recommend_comment' => '2021年の新潟の新米です!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '日本酒6本セット',
            //     'category_id' => '5',
            //     'price' => '3000',
            //     'description' => '新潟こしひかりで作った日本酒です',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '5',
            //     'recommend_comment' => '2020年の新潟のお米で作った日本酒です!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '米ぬか石鹸',
            //     'category_id' => '6',
            //     'price' => '1200',
            //     'description' => '米ぬかで作った石鹸です',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '5',
            //     'recommend_comment' => 'お肌ツルツル間違いなし!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => '牛肉しぐれ煮',
            //     'category_id' => '6',
            //     'price' => '3000',
            //     'description' => '神戸牛をしぐれ煮にしました',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '3',
            //     'recommend_comment' => 'A5ランクの神戸牛で作った贅沢すぎるしぐれ煮｡ご飯の最強のお供!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'トマトジュース',
            //     'category_id' => '6',
            //     'price' => '2200',
            //     'description' => 'トマトジュース',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '4',
            //     'recommend_comment' => '無農薬で作った美味しいトマトをジュースにしました',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'いちごジャム',
            //     'category_id' => '6',
            //     'price' => '2500',
            //     'description' => 'とちおとめを使ったジャムです',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '4',
            //     'recommend_comment' => 'とちおとめで作ったジャムです｡果肉たっぷり!!',
            //     'delete_flag' => '0',
            // ],
            // [
            //     'product_name' => 'お魚フレーク',
            //     'category_id' => '6',
            //     'price' => '1400',
            //     'description' => '新鮮なお魚をフレークにしました',
            //     'sale_status_id' => '1',
            //     'product_status_id' => '1',
            //     'regist_date' => date('Y-m-d H:i:s'),
            //     'product_image_url' => 'no_image.jpg',
            //     'seller_id' => '2',
            //     'recommend_comment' => '新鮮なお魚をフレークに!絶妙な味付けでご飯がすすみます!',
            //     'delete_flag' => '0',
            // ],
        ]);
    }
}
